apiVersion: v2
name: edc
description: A Helm chart for deploying an EDC for the BPDM environment
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tractusx-connector
    alias: txdc
    version: 0.5.0
    repository: https://eclipse-tractusx.github.io/charts/dev
  - name: opensearch
    version: 2.4.0
    repository: https://opensearch-project.github.io/helm-charts/
    alias: opensearch
    condition: opensearch.enabled